#update Repository
RUN apt-get update -y
 
# Install Apache
RUN apt-get install -y apache2
 
#Install PHP Modules
RUN yum install php php-mysql
 
#Copy Application Files
RUN rm -rf /var/www/html/*
ADD dockerfile /var/www/html
 
#Configure Apache [Optional]
RUN chown -R www.data:www.data /var/www
ENV APACHE_RUN_USER www.data
ENV APACHE_RUN_GROUP www.data
ENV APACHE_LOG_DIR /var/log/apache2

#Open port 80
EXPOSE 80
 
#Start Apache Service
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
